export const routes = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  terms: "/terms",
  privacy: "/privacy",
  dashboard: "/dashboard",
  newDesign: "/new-design",
  projects: "/projects",
  team: "/team",
  billing: "/billing",
  settings: "/settings",
  support: "/support",
  superAdmin: {
    dashboard: "/super-admin",
    companies: "/super-admin/companies",
    users: "/super-admin/users",
    subscriptions: "/super-admin/subscriptions",
    support: "/super-admin/support",
  },
  estimator: {
    dashboard: "/estimator",
    newDesign: "/estimator/new-design",
    projects: "/estimator/projects",
    settings: "/estimator/settings",
    support: "/estimator/support",
  },
  engineer: {
    dashboard: "/engineer",
    projects: "/engineer/projects",
    settings: "/engineer/settings",
    support: "/engineer/support",
  },
} as const;
