export const routes = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  verifyOtp: "/verify-otp",
  terms: "/terms",
  privacy: "/privacy",
  dashboard: "/company/dashboard",
  newDesign: "/company/new-design",
  projects: "/company/projects",
  team: "/company/team",
  billing: "/company/billing",
  settings: "/company/settings",
  support: "/company/support",
  // notification: "/company/notifications",
  superAdmin: {
    dashboard: "/super-admin",
    companies: "/super-admin/companies",
    users: "/super-admin/users",
    subscriptions: "/super-admin/subscriptions",
    support: "/super-admin/support",
    notification: "/super-admin/notifications",
  },
  estimator: {
    dashboard: "/estimator",
    newDesign: "/estimator/new-design",
    projects: "/estimator/projects",
    settings: "/estimator/settings",
    support: "/estimator/support",
    // notification: "/estimator/notifications",
  },
  engineer: {
    dashboard: "/engineer",
    projects: "/engineer/projects",
    settings: "/engineer/settings",
    support: "/engineer/support",
    // notification: "/engineer/notifications",
  },
} as const;
